INSERT INTO USER (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD) VALUES ('Nick', 'Steger', 'nsteger', 'password');

INSERT INTO EVENT (NAME, INFO, EVENT_DATETIME, USER_ID) VALUES ('Family Christmas', 'Steger Family Christmas', '2017-12-30 12:00:00', 1);
INSERT INTO EVENT (NAME, INFO, EVENT_DATETIME, USER_ID) VALUES ('Christmas', 'Want not', '2017-12-25 00:00:00', 1);
INSERT INTO EVENT (NAME, INFO, EVENT_DATETIME, USER_ID) VALUES ('Christmas Eve', 'Ask not', '2017-12-24 00:00:00', 1);

INSERT INTO USER_ROLE (USERNAME, ROLE) VALUES ('nsteger', 'ROLE_USER');
INSERT INTO USER_ROLE (USERNAME, ROLE) VALUES ('nsteger', 'ROLE_ADMIN');
