CREATE TABLE EVENT(
  EVENT_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NAME VARCHAR(32) NOT NULL,
  INFO VARCHAR(255),
  EVENT_DATETIME DATETIME NOT NULL,
  USER_ID BIGINT NOT NULL
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  EMAIL VARCHAR(255) NOT NULL,
  HASHED_PASSWORD VARCHAR(64) NOT NULL
);

ALTER TABLE EVENT ADD FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);
CREATE INDEX IDX_EVENT_DATETIME_ ON EVENT (EVENT_DATETIME);
