CREATE TABLE EVENT(
  EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  INFO VARCHAR(200),
  EVENT_DATETIME DATETIME NOT NULL,
  USER_ID BIGINT NOT NULL
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  USERNAME VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
);

CREATE TABLE USER_ROLE(
  USER_ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(32) NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  UNIQUE (USERNAME, ROLE)
);

ALTER TABLE EVENT ADD FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);
ALTER TABLE USER_ROLE ADD FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME);
CREATE INDEX IDX_EVENT_DATETIME_ ON EVENT (EVENT_DATETIME);
