CREATE TABLE EVENT(
  EVENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  INFO VARCHAR(200),
  EVENT_DATETIME DATETIME NOT NULL,
  USER_ID BIGINT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  USERNAME VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL
);

CREATE TABLE USER_ROLE(
  USER_ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  ROLE VARCHAR(255) NOT NULL,
  UNIQUE (USER_ID, ROLE),
  FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

CREATE INDEX IDX_EVENT_DATETIME_ ON EVENT (EVENT_DATETIME);
